version: '3.2'
services:
    database:
        image: mongo:4.2.14
        networks:
            - webnet
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password123
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3

    hold-my-csv:
        build: .
        ports:
            - 80:3000
        networks:
            - webnet
        environment:
            DATABASE_URI: mongodb://root:password123@database/admin
            PORT: 3000
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3

networks:
    webnet:
